### ISSUE TITLE
Home page search breaks on occasion

### ISSUE THREAD

**Issue by taylor-chen** [UWFlow/rmc#225]
This only happened a few times but, when I searched for a course from the home page `https://uwflow.com/`, there was no drop down. When I pressed enter nothing changed except the url changed to `https://uwflow.com/?`. My search queries were `econ` or `ece`.

I noticed the only time this happened was when I went to `https://uwflow.com/` directly. When I had been on the site for a while and navigated back to the home page this doesn't happen.

FYI, this was a bit annoying when it did happen but it was hard to intentionally recreate.

**Comment by JGulbronson** [comment]
Hey Taylor, I suspect that was caused because of the caching we do. Essentially, when you go to the page for the first time, it will cache the items you can search. If it hadn't finished yet, that would cause the issue you experienced, and be tough to replicate after.

You should be able to repro this if you use an incognito browser, which won't have the items in local storage. It'll have to cache them again, but until then you can't search. (Caching usually takes 5-10 seconds)

I'm gonna mark this as closed for now, but feel free to re-open if you find it was something else.
